# -*- coding: utf-8 -*-
"""Localised text for the admin dashboard.

Kept apart from admin_panel.py so the panel file stays about behaviour. Every
language must define exactly the same key set — admin_panel.init() asserts it.

Asset names are *not* here: resources, units and buildings are data now, so
their labels live in the asset_labels table. See asset_catalog.py.
"""

# ---------------------------------------------------------------------------
# Toggleable features. The key is what main*.py passes to feature_enabled().
# ---------------------------------------------------------------------------

FEATURES = ('assets', 'upgrade', 'statement', 'private_message', 'treaty',
            'attack', 'trade', 'weekly_update', 'setlord')

# Actions written to admin_log; label lives under 'act_<name>' in STRINGS.
ACTIONS = ('asset_edit', 'feature_toggle', 'weekly_update', 'reset_country', 'lord_assign',
           'admin_add', 'admin_remove', 'trade_photo', 'war_photo',
           'trade_config', 'chokepoint_owner', 'group_home',
           'asset_add', 'asset_type_edit', 'asset_hide', 'asset_cost')

# CatalogError codes that get their own message; anything else falls back to
# 'err_generic'. Kept next to the strings so the two stay in step.
CATALOG_ERRORS = ('bad_key', 'exists', 'reserved', 'column_exists', 'bad_kind', 'builtin',
                  'bad_produces', 'not_a_building', 'not_a_resource', 'bad_resource', 'unknown')

STRINGS = {
    'fa': {
        'not_admin': "شما ادمین نیستید.",
        'not_owner': "فقط مالک ربات می‌تواند این کار را انجام دهد.",
        'err_generic': "خطایی رخ داد. دوباره تلاش کنید.",
        'feature_disabled': "این بخش توسط مدیریت غیرفعال شده است.",
        'panel_title': "🛡 پنل مدیریت\n<blockquote>👑 مالک: {owner}\n👤 ادمین‌ها: {admins}\n"
                       "🏳 گروه‌ها: {groups}\n⚙️ بخش‌های فعال: {on}/{total}</blockquote>",
        'btn_stats': "📊 آمار کلی",
        'btn_eco': "💰 اقتصاد",
        'btn_mil': "⚔️ وضعیت نظامی",
        'btn_features': "⚙️ فعال/غیرفعال کردن بخش‌ها",
        'btn_logs': "🧾 گزارش اقدامات",
        'btn_admins': "👑 مدیران",
        'btn_trade_photo': "🖼 عکس تجارت",
        'btn_war_photo': "🖼 عکس‌های جنگ",
        'btn_trade_adm': "🌍 مدیریت تجارت",
        'btn_reset': "♻️ بازنشانی دارایی کشور",
        'btn_game_menu': "🎮 منوی بازی",
        'btn_back': "🔙 بازگشت",
        'btn_prev': "➡️ قبلی",
        'btn_next': "بعدی ⬅️",
        'btn_per_group': "🏳 مشاهده به تفکیک گروه",
        'no_groups': "هنوز هیچ گروهی ثبت نشده است.",
        'stats_title': "📊 آمار کلی\n<blockquote>🏳 گروه‌ها: {groups}\n👤 لردها: {lords}\n"
                       "💰 مجموع ثروت: {wealth}\n⚔️ مجموع نیروها: {troops}\n"
                       "🏭 مجموع ساختمان‌ها: {buildings}\n"
                       "🚢 تجارت‌های فعال: {active}\n📨 پیشنهادهای در انتظار: {offered}\n"
                       "✅ تجارت‌های کامل‌شده: {done}</blockquote>",
        'eco_title': "💰 اقتصاد جهانی\n<blockquote>{lines}</blockquote>\n"
                     "🏆 ثروتمندترین: {richest}",
        'mil_title': "⚔️ وضعیت نظامی جهانی\n<blockquote>{lines}</blockquote>\n"
                     "🏆 قوی‌ترین ارتش: {strongest}",
        'group_list_title': "🏳 گروه را انتخاب کنید (صفحه {p} از {n}):",
        'group_card': "🏳 <b>{title}</b>\n👤 لرد: {lord}\n\n"
                      "💰 دارایی:\n<blockquote>{resources}</blockquote>\n"
                      "⚔️ ارتش:\n<blockquote>{units}</blockquote>\n"
                      "🏭 ساختمان‌ها:\n<blockquote>{buildings}</blockquote>\n"
                      "🚢 تجارت: فعال {active} | کامل‌شده {done}\n"
                      "⚓️ موقعیت دریایی: {home_sea} | 🏔 موقعیت زمینی: {home_land}",
        'unset': "تعیین نشده",
        'nobody': "ندارد",
        'feat_title': "⚙️ بخش‌های ربات — برای تغییر وضعیت روی هر مورد بزنید:",
        'feat_on': "✅",
        'feat_off': "❌",
        'feat_toggled': "{name}: {state}",
        'feat_assets': "💰 دارایی",
        'feat_upgrade': "🛠️ ارتقا",
        'feat_statement': "🙌 بیانیه",
        'feat_private_message': "✉️ پیام خصوصی",
        'feat_treaty': "📜 معاهده",
        'feat_attack': "⚔️ لشکرکشی",
        'feat_trade': "🚢 تجارت جهانی",
        'feat_weekly_update': "🔨 آپ هفتگی",
        'feat_setlord': "👤 ثبت لرد",
        'log_title': "🧾 گزارش اقدامات (صفحه {p} از {n}):",
        'log_empty': "هنوز هیچ اقدامی ثبت نشده است.",
        'log_row': "▫️ <b>{action}</b> — {actor}\n   {target}{detail}\n   🕓 {ts}",
        'act_asset_edit': "تغییر دارایی",
        'act_feature_toggle': "تغییر وضعیت بخش",
        'act_weekly_update': "آپ هفتگی",
        'act_reset_country': "بازنشانی دارایی کشور",
        'act_lord_assign': "تعیین لرد",
        'act_admin_add': "افزودن ادمین",
        'act_admin_remove': "حذف ادمین",
        'act_trade_photo': "عکس تجارت",
        'act_war_photo': "عکس جنگ",
        'act_trade_config': "تنظیمات تجارت",
        'act_chokepoint_owner': "مالکیت گذرگاه",
        'act_group_home': "موقعیت تجاری گروه",
        'adm_title': "👑 مدیران ربات\n<blockquote>👑 مالک: {owner}</blockquote>\n"
                     "برای حذف روی یک ادمین بزنید:",
        'adm_none': "غیر از مالک، ادمین دیگری وجود ندارد.",
        'btn_add_admin': "➕ افزودن ادمین",
        'adm_add_ask': "پیامی از کاربر مورد نظر را فوروارد کنید یا شناسه عددی او را بفرستید:",
        'adm_added': "✅ {u} به ادمین‌ها اضافه شد.",
        'adm_removed': "🗑 {u} از ادمین‌ها حذف شد.",
        'adm_exists': "این کاربر از قبل ادمین است.",
        'adm_is_owner': "این کاربر مالک ربات است و همیشه دسترسی کامل دارد.",
        'adm_bad_id': "شناسه معتبر نیست. یک عدد بفرستید یا پیامی از کاربر را فوروارد کنید.",
        'reset_pick': "♻️ کدام کشور به حالت اولیه بازگردانده شود؟ (صفحه {p} از {n})",
        'reset_confirm': "♻️ آیا مطمئنید که دارایی‌ها، نیروها و ساختمان‌های <b>{title}</b> "
                         "به مقادیر اولیه بازگردانده شوند؟\n"
                         "معاهدات و موقعیت‌های تجاری دست نخورده باقی می‌مانند. "
                         "این کار قابل بازگشت نیست.",
        'btn_confirm_reset': "✅ بله، بازنشانی کن",
        'reset_done': "♻️ دارایی‌های <b>{title}</b> به حالت اولیه بازگشت.",
        'war_photo_title': "🖼 عکس‌های لشکرکشی — برای تنظیم روی هر مورد بزنید:",
        'wp_land': "🐫 عکس لشکرکشی زمینی",
        'wp_sea': "🚢 عکس لشکرکشی دریایی",
        'wp_set': "تنظیم شده",
        'wp_unset': "تنظیم نشده",
        'wp_ask': "اکنون عکس مورد نظر را بفرستید:",
        'wp_saved': "✅ عکس {kind} ذخیره شد.",
        'wp_cleared': "🗑 عکس {kind} حذف شد.",
        'wp_not_photo': "این پیام عکس نیست؛ عملیات لغو شد.",
        'btn_wp_clear': "🗑 حذف عکس",
        'setlord_group_only': "این دستور فقط در گروه‌ها قابل استفاده است.",
        'setlord_not_admin': "فقط ادمین ربات می‌تواند لرد تعیین کند.",
        'setlord_need_reply': "روی پیام بازیکنی که می‌خواهید لرد شود ریپلای کنید و /setlord بزنید.",
        'setlord_bot_target': "نمی‌توان یک ربات را به عنوان لرد ثبت کرد.",
        'setlord_done': "👤 {u} به عنوان لرد این گروه ثبت شد.",
        'setlord_already': "👤 {u} از قبل لرد این گروه است.",
        'act_asset_add': "افزودن نوع دارایی",
        'act_asset_type_edit': "ویرایش نوع دارایی",
        'act_asset_hide': "حذف نوع دارایی",
        'act_asset_cost': "هزینه ارتقا",
        'btn_catalog': "🧩 دارایی‌ها و واحدها",
        'cat_title': "🧩 فهرست دارایی‌های بازی — یک دسته را انتخاب کنید:\n"
                     "<blockquote>📦 منابع: {resources}\n⚔️ واحدها: {units}\n"
                     "🏭 ساختمان‌ها: {buildings}</blockquote>",
        'kind_resource': "📦 منابع",
        'kind_unit': "⚔️ واحدها",
        'kind_building': "🏭 ساختمان‌ها",
        'cat_list_title': "{kind} (صفحه {p} از {n}) — برای ویرایش روی یکی بزنید:",
        'cat_hidden_mark': "🚫",
        'btn_cat_add': "➕ افزودن نوع جدید",
        'cat_entry': "🧩 <b>{label}</b>\n<blockquote>🔑 کلید: <code>{key}</code>\n"
                     "📁 دسته: {kind}\n🎁 مقدار اولیه: {default}\n{extra}</blockquote>{note}",
        'cat_extra_building': "🏭 تولید می‌کند: {produces}\n📈 تولید هر سطح در هفته: {output}\n"
                              "💸 هزینه ارتقا: {costs}",
        'cat_extra_resource': "🚢 قابل تجارت: {tradeable}",
        'cat_produces_none': "چیزی تولید نمی‌کند",
        'cat_costs_none': "رایگان",
        'cat_builtin_note': "\n\nℹ️ این نوع همراه بازی آمده است؛ قابل ویرایش هست اما حذف نمی‌شود.",
        'cat_hidden_note': "\n\n🚫 این نوع از بازی حذف شده است. مقادیر ذخیره‌شده دست‌نخورده‌اند و "
                           "با بازگرداندن دوباره ظاهر می‌شوند.",
        'btn_cat_rename': "✏️ تغییر نام",
        'btn_cat_default': "🎁 مقدار اولیه",
        'btn_cat_output': "📈 تولید",
        'btn_cat_tradeable': "🚢 قابل تجارت",
        'btn_cat_costs': "💸 هزینه ارتقا",
        'btn_cat_hide': "🗑 حذف از بازی",
        'btn_cat_unhide': "♻️ بازگرداندن به بازی",
        'cat_ask_key': "کلید انگلیسی نوع جدید را بفرستید (حروف کوچک و زیرخط، مثل archers):",
        'cat_ask_label': "نام نمایشی به {lang} را بفرستید (می‌توانید ایموجی هم بگذارید):",
        'cat_ask_default': "مقدار اولیه هر کشور برای این نوع را وارد کنید:",
        'cat_bad_number': "مقدار معتبر نیست. یک عدد صحیح غیرمنفی بفرستید.",
        'cat_ask_output': "در هر آپ هفتگی، هر سطح این ساختمان چه مقدار تولید کند؟",
        'cat_ask_cost': "هزینه ارتقا بر حسب {res} چقدر باشد؟ (صفر یعنی نیازی نیست)",
        'cat_pick_produces': "این ساختمان چه چیزی تولید می‌کند؟",
        'btn_produces_none': "🚫 هیچ‌چیز",
        'cat_costs_title': "💸 هزینه یک سطح از {label} — برای تغییر روی هر منبع بزنید:",
        'cat_added': "✅ «{label}» به بازی اضافه شد.",
        'cat_renamed': "✅ نام‌ها به‌روزرسانی شد.",
        'cat_default_set': "✅ مقدار اولیه روی {value} تنظیم شد.",
        'cat_output_set': "✅ تولید به‌روزرسانی شد.",
        'cat_tradeable_on': "✅ این منبع اکنون قابل تجارت است.",
        'cat_tradeable_off': "🚫 این منبع دیگر قابل تجارت نیست.",
        'cat_cost_set': "✅ هزینه به‌روزرسانی شد.",
        'cat_hidden': "🗑 «{label}» از بازی حذف شد.",
        'cat_unhidden': "♻️ «{label}» به بازی بازگشت.",
        'cat_lang_fa': "فارسی",
        'cat_lang_en': "انگلیسی",
        'cat_lang_tr': "ترکی",
        'cat_yes': "بله",
        'cat_no': "خیر",
        'cat_err_bad_key': "❌ کلید نامعتبر است. فقط حروف کوچک انگلیسی، عدد و زیرخط؛ "
                           "با حرف شروع شود و بین ۲ تا ۳۱ کاراکتر باشد.",
        'cat_err_exists': "❌ نوعی با این کلید از قبل وجود دارد.",
        'cat_err_reserved': "❌ این کلید رزرو شده است.",
        'cat_err_column_exists': "❌ ستونی با این نام از قبل در پایگاه داده هست.",
        'cat_err_bad_kind': "❌ دسته نامعتبر است.",
        'cat_err_builtin': "❌ انواع پیش‌فرض بازی قابل حذف نیستند.",
        'cat_err_bad_produces': "❌ یک ساختمان فقط می‌تواند منبع یا واحد تولید کند.",
        'cat_err_not_a_building': "❌ این مورد ساختمان نیست.",
        'cat_err_not_a_resource': "❌ این مورد منبع نیست.",
        'cat_err_bad_resource': "❌ منبع نامعتبر است.",
        'cat_err_unknown': "❌ چنین نوعی وجود ندارد.",
    },
    'en': {
        'not_admin': "You are not an admin.",
        'not_owner': "Only the bot owner can do that.",
        'err_generic': "Something went wrong. Please try again.",
        'feature_disabled': "This section has been disabled by the administration.",
        'panel_title': "🛡 Admin Panel\n<blockquote>👑 Owner: {owner}\n👤 Admins: {admins}\n"
                       "🏳 Groups: {groups}\n⚙️ Enabled sections: {on}/{total}</blockquote>",
        'btn_stats': "📊 Statistics",
        'btn_eco': "💰 Economy",
        'btn_mil': "⚔️ Military",
        'btn_features': "⚙️ Enable/disable sections",
        'btn_logs': "🧾 Action log",
        'btn_admins': "👑 Admins",
        'btn_trade_photo': "🖼 Trade photo",
        'btn_war_photo': "🖼 War photos",
        'btn_trade_adm': "🌍 Trade administration",
        'btn_reset': "♻️ Reset a country",
        'btn_game_menu': "🎮 Game menu",
        'btn_back': "🔙 Back",
        'btn_prev': "⬅️ Prev",
        'btn_next': "Next ➡️",
        'btn_per_group': "🏳 Break down by group",
        'no_groups': "No group has registered yet.",
        'stats_title': "📊 Global statistics\n<blockquote>🏳 Groups: {groups}\n👤 Lords: {lords}\n"
                       "💰 Total wealth: {wealth}\n⚔️ Total troops: {troops}\n"
                       "🏭 Total buildings: {buildings}\n"
                       "🚢 Active trades: {active}\n📨 Pending offers: {offered}\n"
                       "✅ Completed trades: {done}</blockquote>",
        'eco_title': "💰 World economy\n<blockquote>{lines}</blockquote>\n"
                     "🏆 Richest: {richest}",
        'mil_title': "⚔️ World military\n<blockquote>{lines}</blockquote>\n"
                     "🏆 Strongest army: {strongest}",
        'group_list_title': "🏳 Choose a group (page {p} of {n}):",
        'group_card': "🏳 <b>{title}</b>\n👤 Lord: {lord}\n\n"
                      "💰 Resources:\n<blockquote>{resources}</blockquote>\n"
                      "⚔️ Army:\n<blockquote>{units}</blockquote>\n"
                      "🏭 Buildings:\n<blockquote>{buildings}</blockquote>\n"
                      "🚢 Trades: active {active} | completed {done}\n"
                      "⚓️ Sea location: {home_sea} | 🏔 Land location: {home_land}",
        'unset': "not set",
        'nobody': "none",
        'feat_title': "⚙️ Bot sections — tap one to toggle it:",
        'feat_on': "✅",
        'feat_off': "❌",
        'feat_toggled': "{name}: {state}",
        'feat_assets': "💰 Assets",
        'feat_upgrade': "🛠️ Upgrade",
        'feat_statement': "🙌 Statement",
        'feat_private_message': "✉️ Private message",
        'feat_treaty': "📜 Treaty",
        'feat_attack': "⚔️ Military campaign",
        'feat_trade': "🚢 World trade",
        'feat_weekly_update': "🔨 Weekly update",
        'feat_setlord': "👤 Lord registration",
        'log_title': "🧾 Admin action log (page {p} of {n}):",
        'log_empty': "No admin action has been recorded yet.",
        'log_row': "▫️ <b>{action}</b> — {actor}\n   {target}{detail}\n   🕓 {ts}",
        'act_asset_edit': "asset edited",
        'act_feature_toggle': "section toggled",
        'act_weekly_update': "weekly update",
        'act_reset_country': "country reset",
        'act_lord_assign': "lord assigned",
        'act_admin_add': "admin added",
        'act_admin_remove': "admin removed",
        'act_trade_photo': "trade photo",
        'act_war_photo': "war photo",
        'act_trade_config': "trade setting",
        'act_chokepoint_owner': "chokepoint owner",
        'act_group_home': "group trade location",
        'adm_title': "👑 Bot admins\n<blockquote>👑 Owner: {owner}</blockquote>\n"
                     "Tap an admin to remove them:",
        'adm_none': "There are no admins besides the owner.",
        'btn_add_admin': "➕ Add admin",
        'adm_add_ask': "Forward a message from the user, or send their numeric id:",
        'adm_added': "✅ {u} was added to the admins.",
        'adm_removed': "🗑 {u} was removed from the admins.",
        'adm_exists': "That user is already an admin.",
        'adm_is_owner': "That user is the bot owner and always has full access.",
        'adm_bad_id': "That is not a valid id. Send a number or forward a message from the user.",
        'reset_pick': "♻️ Which country should be reset to its initial state? (page {p} of {n})",
        'reset_confirm': "♻️ Reset the resources, troops and buildings of <b>{title}</b> "
                         "to their starting values?\n"
                         "Treaties and trade locations are left untouched. "
                         "This cannot be undone.",
        'btn_confirm_reset': "✅ Yes, reset it",
        'reset_done': "♻️ The assets of <b>{title}</b> were reset to their initial values.",
        'war_photo_title': "🖼 Campaign photos — tap one to set it:",
        'wp_land': "🐫 Land campaign photo",
        'wp_sea': "🚢 Sea campaign photo",
        'wp_set': "set",
        'wp_unset': "not set",
        'wp_ask': "Send the photo now:",
        'wp_saved': "✅ The {kind} photo was saved.",
        'wp_cleared': "🗑 The {kind} photo was removed.",
        'wp_not_photo': "That message is not a photo; the operation was cancelled.",
        'btn_wp_clear': "🗑 Remove photo",
        'setlord_group_only': "This command can only be used in groups.",
        'setlord_not_admin': "Only a bot admin can appoint a lord.",
        'setlord_need_reply': "Reply to the message of the player you want to make lord, then send /setlord.",
        'setlord_bot_target': "A bot cannot be registered as a lord.",
        'setlord_done': "👤 {u} has been registered as the lord of this group.",
        'setlord_already': "👤 {u} is already the lord of this group.",
        'act_asset_add': "asset type added",
        'act_asset_type_edit': "asset type edited",
        'act_asset_hide': "asset type removed",
        'act_asset_cost': "upgrade cost",
        'btn_catalog': "🧩 Assets & units",
        'cat_title': "🧩 The game's asset catalog — pick a category:\n"
                     "<blockquote>📦 Resources: {resources}\n⚔️ Units: {units}\n"
                     "🏭 Buildings: {buildings}</blockquote>",
        'kind_resource': "📦 Resources",
        'kind_unit': "⚔️ Units",
        'kind_building': "🏭 Buildings",
        'cat_list_title': "{kind} (page {p} of {n}) — tap one to edit it:",
        'cat_hidden_mark': "🚫",
        'btn_cat_add': "➕ Add a new type",
        'cat_entry': "🧩 <b>{label}</b>\n<blockquote>🔑 Key: <code>{key}</code>\n"
                     "📁 Category: {kind}\n🎁 Starting amount: {default}\n{extra}</blockquote>{note}",
        'cat_extra_building': "🏭 Produces: {produces}\n📈 Per level per week: {output}\n"
                              "💸 Upgrade cost: {costs}",
        'cat_extra_resource': "🚢 Tradeable: {tradeable}",
        'cat_produces_none': "nothing",
        'cat_costs_none': "free",
        'cat_builtin_note': "\n\nℹ️ This type shipped with the game — it can be retuned but not removed.",
        'cat_hidden_note': "\n\n🚫 This type has been removed from the game. Its stored values are "
                           "untouched and come back if you restore it.",
        'btn_cat_rename': "✏️ Rename",
        'btn_cat_default': "🎁 Starting amount",
        'btn_cat_output': "📈 Production",
        'btn_cat_tradeable': "🚢 Tradeable",
        'btn_cat_costs': "💸 Upgrade cost",
        'btn_cat_hide': "🗑 Remove from the game",
        'btn_cat_unhide': "♻️ Restore to the game",
        'cat_ask_key': "Send the internal key for the new type (lowercase and underscores, e.g. archers):",
        'cat_ask_label': "Send the display name in {lang} (emoji are welcome):",
        'cat_ask_default': "How much of this should each country start with?",
        'cat_bad_number': "That is not a valid amount. Send a non-negative whole number.",
        'cat_ask_output': "How much should each level of this building produce per weekly update?",
        'cat_ask_cost': "How much {res} should one upgrade cost? (zero means none)",
        'cat_pick_produces': "What does this building produce?",
        'btn_produces_none': "🚫 Nothing",
        'cat_costs_title': "💸 Cost of one level of {label} — tap a resource to change it:",
        'cat_added': "✅ “{label}” was added to the game.",
        'cat_renamed': "✅ The names were updated.",
        'cat_default_set': "✅ The starting amount is now {value}.",
        'cat_output_set': "✅ Production updated.",
        'cat_tradeable_on': "✅ This resource can now be traded.",
        'cat_tradeable_off': "🚫 This resource can no longer be traded.",
        'cat_cost_set': "✅ The cost was updated.",
        'cat_hidden': "🗑 “{label}” was removed from the game.",
        'cat_unhidden': "♻️ “{label}” is back in the game.",
        'cat_lang_fa': "Persian",
        'cat_lang_en': "English",
        'cat_lang_tr': "Turkish",
        'cat_yes': "yes",
        'cat_no': "no",
        'cat_err_bad_key': "❌ Invalid key. Lowercase letters, digits and underscores only; "
                           "must start with a letter and be 2 to 31 characters long.",
        'cat_err_exists': "❌ A type with that key already exists.",
        'cat_err_reserved': "❌ That key is reserved.",
        'cat_err_column_exists': "❌ A database column with that name already exists.",
        'cat_err_bad_kind': "❌ Invalid category.",
        'cat_err_builtin': "❌ Types that shipped with the game cannot be removed.",
        'cat_err_bad_produces': "❌ A building can only produce a resource or a unit.",
        'cat_err_not_a_building': "❌ That entry is not a building.",
        'cat_err_not_a_resource': "❌ That entry is not a resource.",
        'cat_err_bad_resource': "❌ Invalid resource.",
        'cat_err_unknown': "❌ No such type.",
    },
    'tr': {
        'not_admin': "Yönetici değilsiniz.",
        'not_owner': "Bunu yalnızca bot sahibi yapabilir.",
        'err_generic': "Bir hata oluştu. Lütfen tekrar deneyin.",
        'feature_disabled': "Bu bölüm yönetim tarafından devre dışı bırakıldı.",
        'panel_title': "🛡 Yönetim Paneli\n<blockquote>👑 Sahip: {owner}\n👤 Yöneticiler: {admins}\n"
                       "🏳 Gruplar: {groups}\n⚙️ Etkin bölümler: {on}/{total}</blockquote>",
        'btn_stats': "📊 İstatistikler",
        'btn_eco': "💰 Ekonomi",
        'btn_mil': "⚔️ Askeri durum",
        'btn_features': "⚙️ Bölümleri aç/kapat",
        'btn_logs': "🧾 İşlem kaydı",
        'btn_admins': "👑 Yöneticiler",
        'btn_trade_photo': "🖼 Ticaret fotoğrafı",
        'btn_war_photo': "🖼 Savaş fotoğrafları",
        'btn_trade_adm': "🌍 Ticaret yönetimi",
        'btn_reset': "♻️ Ülkeyi sıfırla",
        'btn_game_menu': "🎮 Oyun menüsü",
        'btn_back': "🔙 Geri",
        'btn_prev': "⬅️ Önceki",
        'btn_next': "Sonraki ➡️",
        'btn_per_group': "🏳 Gruplara göre ayır",
        'no_groups': "Henüz hiçbir grup kayıtlı değil.",
        'stats_title': "📊 Genel istatistikler\n<blockquote>🏳 Gruplar: {groups}\n👤 Lordlar: {lords}\n"
                       "💰 Toplam servet: {wealth}\n⚔️ Toplam asker: {troops}\n"
                       "🏭 Toplam bina: {buildings}\n"
                       "🚢 Etkin ticaretler: {active}\n📨 Bekleyen teklifler: {offered}\n"
                       "✅ Tamamlanan ticaretler: {done}</blockquote>",
        'eco_title': "💰 Dünya ekonomisi\n<blockquote>{lines}</blockquote>\n"
                     "🏆 En zengin: {richest}",
        'mil_title': "⚔️ Dünya askeri gücü\n<blockquote>{lines}</blockquote>\n"
                     "🏆 En güçlü ordu: {strongest}",
        'group_list_title': "🏳 Bir grup seçin ({p}/{n}. sayfa):",
        'group_card': "🏳 <b>{title}</b>\n👤 Lord: {lord}\n\n"
                      "💰 Kaynaklar:\n<blockquote>{resources}</blockquote>\n"
                      "⚔️ Ordu:\n<blockquote>{units}</blockquote>\n"
                      "🏭 Binalar:\n<blockquote>{buildings}</blockquote>\n"
                      "🚢 Ticaret: etkin {active} | tamamlanan {done}\n"
                      "⚓️ Deniz konumu: {home_sea} | 🏔 Kara konumu: {home_land}",
        'unset': "ayarlanmadı",
        'nobody': "yok",
        'feat_title': "⚙️ Bot bölümleri — durumu değiştirmek için birine dokunun:",
        'feat_on': "✅",
        'feat_off': "❌",
        'feat_toggled': "{name}: {state}",
        'feat_assets': "💰 Varlıklar",
        'feat_upgrade': "🛠️ Yükseltme",
        'feat_statement': "🙌 Bildiri",
        'feat_private_message': "✉️ Özel mesaj",
        'feat_treaty': "📜 Antlaşma",
        'feat_attack': "⚔️ Askeri sefer",
        'feat_trade': "🚢 Dünya ticareti",
        'feat_weekly_update': "🔨 Haftalık güncelleme",
        'feat_setlord': "👤 Lord kaydı",
        'log_title': "🧾 Yönetici işlem kaydı ({p}/{n}. sayfa):",
        'log_empty': "Henüz hiçbir yönetici işlemi kaydedilmedi.",
        'log_row': "▫️ <b>{action}</b> — {actor}\n   {target}{detail}\n   🕓 {ts}",
        'act_asset_edit': "varlık düzenlendi",
        'act_feature_toggle': "bölüm değiştirildi",
        'act_weekly_update': "haftalık güncelleme",
        'act_reset_country': "ülke sıfırlandı",
        'act_lord_assign': "lord atandı",
        'act_admin_add': "yönetici eklendi",
        'act_admin_remove': "yönetici çıkarıldı",
        'act_trade_photo': "ticaret fotoğrafı",
        'act_war_photo': "savaş fotoğrafı",
        'act_trade_config': "ticaret ayarı",
        'act_chokepoint_owner': "geçit sahipliği",
        'act_group_home': "grup ticaret konumu",
        'adm_title': "👑 Bot yöneticileri\n<blockquote>👑 Sahip: {owner}</blockquote>\n"
                     "Çıkarmak için bir yöneticiye dokunun:",
        'adm_none': "Sahip dışında yönetici yok.",
        'btn_add_admin': "➕ Yönetici ekle",
        'adm_add_ask': "Kullanıcıdan bir mesaj iletin veya sayısal kimliğini gönderin:",
        'adm_added': "✅ {u} yöneticilere eklendi.",
        'adm_removed': "🗑 {u} yöneticilerden çıkarıldı.",
        'adm_exists': "Bu kullanıcı zaten yönetici.",
        'adm_is_owner': "Bu kullanıcı bot sahibidir ve her zaman tam yetkilidir.",
        'adm_bad_id': "Geçerli bir kimlik değil. Bir sayı gönderin veya kullanıcıdan bir mesaj iletin.",
        'reset_pick': "♻️ Hangi ülke başlangıç durumuna döndürülsün? ({p}/{n}. sayfa)",
        'reset_confirm': "♻️ <b>{title}</b> grubunun kaynakları, askerleri ve binaları "
                         "başlangıç değerlerine döndürülsün mü?\n"
                         "Antlaşmalar ve ticaret konumları değişmez. "
                         "Bu işlem geri alınamaz.",
        'btn_confirm_reset': "✅ Evet, sıfırla",
        'reset_done': "♻️ <b>{title}</b> grubunun varlıkları başlangıç değerlerine döndürüldü.",
        'war_photo_title': "🖼 Sefer fotoğrafları — ayarlamak için birine dokunun:",
        'wp_land': "🐫 Kara seferi fotoğrafı",
        'wp_sea': "🚢 Deniz seferi fotoğrafı",
        'wp_set': "ayarlandı",
        'wp_unset': "ayarlanmadı",
        'wp_ask': "Fotoğrafı şimdi gönderin:",
        'wp_saved': "✅ {kind} fotoğrafı kaydedildi.",
        'wp_cleared': "🗑 {kind} fotoğrafı kaldırıldı.",
        'wp_not_photo': "Bu mesaj bir fotoğraf değil; işlem iptal edildi.",
        'btn_wp_clear': "🗑 Fotoğrafı kaldır",
        'setlord_group_only': "Bu komut yalnızca gruplarda kullanılabilir.",
        'setlord_not_admin': "Yalnızca bir bot yöneticisi lord atayabilir.",
        'setlord_need_reply': "Lord yapmak istediğiniz oyuncunun mesajını yanıtlayıp /setlord gönderin.",
        'setlord_bot_target': "Bir bot lord olarak kaydedilemez.",
        'setlord_done': "👤 {u} bu grubun lordu olarak kaydedildi.",
        'setlord_already': "👤 {u} zaten bu grubun lordu.",
        'act_asset_add': "varlık türü eklendi",
        'act_asset_type_edit': "varlık türü düzenlendi",
        'act_asset_hide': "varlık türü kaldırıldı",
        'act_asset_cost': "yükseltme maliyeti",
        'btn_catalog': "🧩 Varlıklar ve birimler",
        'cat_title': "🧩 Oyunun varlık kataloğu — bir kategori seçin:\n"
                     "<blockquote>📦 Kaynaklar: {resources}\n⚔️ Birimler: {units}\n"
                     "🏭 Binalar: {buildings}</blockquote>",
        'kind_resource': "📦 Kaynaklar",
        'kind_unit': "⚔️ Birimler",
        'kind_building': "🏭 Binalar",
        'cat_list_title': "{kind} ({p}/{n}. sayfa) — düzenlemek için birine dokunun:",
        'cat_hidden_mark': "🚫",
        'btn_cat_add': "➕ Yeni tür ekle",
        'cat_entry': "🧩 <b>{label}</b>\n<blockquote>🔑 Anahtar: <code>{key}</code>\n"
                     "📁 Kategori: {kind}\n🎁 Başlangıç miktarı: {default}\n{extra}</blockquote>{note}",
        'cat_extra_building': "🏭 Ürettiği: {produces}\n📈 Seviye başına haftalık: {output}\n"
                              "💸 Yükseltme maliyeti: {costs}",
        'cat_extra_resource': "🚢 Ticarete açık: {tradeable}",
        'cat_produces_none': "hiçbir şey",
        'cat_costs_none': "ücretsiz",
        'cat_builtin_note': "\n\nℹ️ Bu tür oyunla birlikte gelir — ayarlanabilir ama kaldırılamaz.",
        'cat_hidden_note': "\n\n🚫 Bu tür oyundan kaldırıldı. Kayıtlı değerleri korunuyor ve "
                           "geri getirildiğinde yeniden görünecek.",
        'btn_cat_rename': "✏️ Yeniden adlandır",
        'btn_cat_default': "🎁 Başlangıç miktarı",
        'btn_cat_output': "📈 Üretim",
        'btn_cat_tradeable': "🚢 Ticarete açık",
        'btn_cat_costs': "💸 Yükseltme maliyeti",
        'btn_cat_hide': "🗑 Oyundan kaldır",
        'btn_cat_unhide': "♻️ Oyuna geri getir",
        'cat_ask_key': "Yeni tür için dahili anahtarı gönderin (küçük harf ve alt çizgi, örn. archers):",
        'cat_ask_label': "{lang} dilindeki görünen adı gönderin (emoji kullanabilirsiniz):",
        'cat_ask_default': "Her ülke bundan ne kadarla başlasın?",
        'cat_bad_number': "Geçersiz miktar. Negatif olmayan bir tam sayı gönderin.",
        'cat_ask_output': "Bu binanın her seviyesi haftalık güncellemede ne kadar üretsin?",
        'cat_ask_cost': "Bir yükseltme ne kadar {res} tutsun? (sıfır: gerekmez)",
        'cat_pick_produces': "Bu bina ne üretiyor?",
        'btn_produces_none': "🚫 Hiçbir şey",
        'cat_costs_title': "💸 {label} için bir seviyenin maliyeti — değiştirmek için bir kaynağa dokunun:",
        'cat_added': "✅ “{label}” oyuna eklendi.",
        'cat_renamed': "✅ Adlar güncellendi.",
        'cat_default_set': "✅ Başlangıç miktarı artık {value}.",
        'cat_output_set': "✅ Üretim güncellendi.",
        'cat_tradeable_on': "✅ Bu kaynak artık ticarete açık.",
        'cat_tradeable_off': "🚫 Bu kaynak artık ticarete açık değil.",
        'cat_cost_set': "✅ Maliyet güncellendi.",
        'cat_hidden': "🗑 “{label}” oyundan kaldırıldı.",
        'cat_unhidden': "♻️ “{label}” yeniden oyunda.",
        'cat_lang_fa': "Farsça",
        'cat_lang_en': "İngilizce",
        'cat_lang_tr': "Türkçe",
        'cat_yes': "evet",
        'cat_no': "hayır",
        'cat_err_bad_key': "❌ Geçersiz anahtar. Yalnızca küçük harf, rakam ve alt çizgi; "
                           "bir harfle başlamalı ve 2-31 karakter olmalı.",
        'cat_err_exists': "❌ Bu anahtara sahip bir tür zaten var.",
        'cat_err_reserved': "❌ Bu anahtar ayrılmış.",
        'cat_err_column_exists': "❌ Bu adda bir veritabanı sütunu zaten var.",
        'cat_err_bad_kind': "❌ Geçersiz kategori.",
        'cat_err_builtin': "❌ Oyunla gelen türler kaldırılamaz.",
        'cat_err_bad_produces': "❌ Bir bina yalnızca kaynak veya birim üretebilir.",
        'cat_err_not_a_building': "❌ Bu girdi bir bina değil.",
        'cat_err_not_a_resource': "❌ Bu girdi bir kaynak değil.",
        'cat_err_bad_resource': "❌ Geçersiz kaynak.",
        'cat_err_unknown': "❌ Böyle bir tür yok.",
    },
}
